item {
  id: 1
  name: 'cirrocumulus'
}

item {
  id: 2
  name: 'cirrostratus'
}

item {
  id: 3
  name: 'cirrus'
}

item {
  id: 4
  name: 'cumulonimbus'
}

item {
  id: 5
  name: 'altocumulus'
}

item {
  id: 6
  name: 'altostratus'
}

item {
  id: 7
  name: 'cumulus'
}

item {
  id: 8
  name: 'nimbostratus'
}

item {
  id: 9
  name: 'stratocumulus'
}

item {
  id: 10
  name: 'lenticularis'
}